### PR TITLE
Add `mpi_serial`

### LINKED ISSUE #9: Add new mpi provider for mpi-serial
### Comment:

We, that is me, @xylar, and @mahf708, would like to add mpi-serial as an mpi provider to conda-forge.

This is motivated by problems with newer versions of ESMF that depend on ParallelIO and are no longer working as `nompi`.
[A comment by @billsacks](https://github.com/conda-forge/esmf-feedstock/pull/102#issuecomment-1533871164) points to mpi-serial as a possible solution.

The `mpi-serial` package is pending in conda-forge/staged-recipes#22793, but to integrate it properly into the conda-forge mpi infrastructure, I believe we need to add a new mpi variant here.

- Is this correct?
- Is it ok to add here?
- Must the variant be called the same as the package, i.e. `mpi-serial`, or would `serial` be ok/preferred?

Thanks for your help, @conda-forge/mpi!

### PR DESCRIPTION
**Pull request by xylar**
This is provided by the `mpi-serial` package.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #9

### CODE REVIEW

**Comment by xylar** [comment]
The `mpi-serial` package is being added in:
https://github.com/conda-forge/staged-recipes/pull/22793

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Review by leofang — APPROVED** [review]
Will wait for one or two business days to let others from @conda-forge/mpi to take a look.

**Comment by xylar** [comment]
@leofang, thanks for fixing the license name.

**Comment by xylar** [comment]
@isuruf  indicated in https://github.com/conda-forge/staged-recipes/pull/22793#discussion_r1193056657 that we want to merge this before merging the `mpi-serial` recipe.  So I'm taking this out of draft mode.  @minrk and @ocefpaf, any feedback before we merge?

**Review by minrk — APPROVED** [review]

**Pull request merged**
