### PR TITLE
Add MS-MPI

### PR DESCRIPTION
**Pull request by leofang**
MNT: Re-rendered with conda-build 3.20.3, conda-smithy 3.8.6, and conda-forge-pinning 2021.01.04.22.18.20

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
cc: @conda-forge/core @isuruf

**Comment by leofang** [comment]
Question: We don't need to bump the build number here?

**Comment by leofang** [comment]
@conda-forge/mpi @conda-forge/core PTAL.

**Review by isuruf — APPROVED** [review]

**Comment by leofang** [comment]
Friendly ping @conda-forge/mpi @conda-forge/core to merge this 🙂

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@conda-forge/core @conda-forge/mpi I added myself as a maintainer. PTAL.

**Comment by isuruf** [comment]
Thanks @leofang. @ocefpaf, @minrk, hope you don't mind.

**Comment by leofang** [comment]
Thanks a ton, @isuruf 🙏

**Pull request merged**
